name: PureEntities
main: milk.pureentities.PureEntities
version: "1.0"
api: ["1.0.0"]

load: STARTUP
author: SW-Team
description: Implement all MCPE entities
website: https://github.com/SW-Team/PureEntities
commands: []