#name, main, version and api are required
name: PureEntities
main: milk.pureentities.PureEntities
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0"
api: ["1.0.0"]

load: STARTUP
author: SW-Team
description: Implement all MCPE entities
website: https://github.com/SW-Team/PureEntities
commands: []